### Start a New Match [POST]
+ Request (application/json)
    {
        "gridsize" : 19,
        "players" : [
        {
            "color" : "white",
            "name" : "bob"
        },
        {
            "color" : "black",
            "name" : "alfred"
        }
        ]
    }
+ Response 201 (application/json)
    + Headers
        Location:/matches/5a003b78-409e-4452-b456-a6f0dcee05bd
    + Body
        {
            "id" : "5a003b78-409e-4452-b456-a6f0dcee05bd",
            "start_at" : "2015-08-05T08:40:51.620Z",
            "gridsize" : 19,
            "turn" : 0,
            "players" : [
                {
                    "color" : "white",
                    "name" : "bob",
                    "score" : 10
                },
                {
                    "color" : "black",
                    "name" : "alfred",
                    "score" : 22
                }
            ]
        }    